name: VPSDeploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag image-server:master
    - name: Stop old Container
      run: |
          docker stop image-server || true
    - name: Remove old container
      run: |
          docker rm image-server || true
    - name: Run new container
      run: |
          docker run -dit --name image-server --network js-store-net image-server:master
